blank_issues_enabled: true
contact_links:
  - name: ðŸ“Œ Faraday Ops â€” Como usar as Issues
    url: https://github.com/wollisellis/nextnutri-bodycomp-mvp
    about: Use os templates abaixo. Se faltar algo, crie issue em branco.
